model: models.py:ModelDR
version: oriented_lp2_k17_zeros_s0
N: 256
activation: GaussActivation
batch_shuffle: true
batch_size: 10
bounds:
- - 0.0
  - 1.0
- - 0.0
  - 1.0
dt: 1.52587890625e-05
epsilon: 0.00390625
kernel_init: zeros
kernel_size:
- 17
- 17
layers:
- 8
- 3
loss_norms:
- - 2
  - 1.0
loss_power: 2.0
lp: 2
lr: 0.0001
num_workers: 0
radius:
- 0.00
- 0.40
seed: 0
train_N: 100
train_reverse: 0.0
train_steps: 1
use_lazy_datasets: false
val_N: 200
val_reverse: 0.0
val_steps: 5

max_epochs: 10000
check_val_every_n_epoch: 100
